apiVersion: v1
kind: Service

metadata:
  name: mysql-service

spec:
  type: ClusterIP
  selector:
    app: mysql-db # 어떤 Pod 와 연결할지
  ports:
    - protocol: TCP # 서비스에 접속하기 위한 프로토콜
      port: 3306 # 쿠버네티스 내부에서 Service에 접속하기 위한 포트 번호
      targetPort: 3306 # 매핑하기 위한 파드의 포트 번호
      # nodePort: 30002 # 외부에서 사용자들이 접근하게 될 포트 번호
