apiVersion: apps/v1
kind: Deployment

metadata:
  name: mysql-deployment

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql-db

  template:
    metadata:
      labels:
        app: mysql-db
    spec:
      containers:
        - name: mysql-container
          image: mysql
          ports:
            - containerPort: 3306
          env: # 참고) mysql 이미지는 환경변수를 적어주어야만 정상적으로 동작한다
            - name: MYSQL_ROOT_PASSWORD # 비밀번호 정의
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: mysql-root-password
            - name: MYSQL_DATABASE # 초기 데이터베이스 정의
              valueFrom:
                configMapKeyRef:
                  name: mysql-config
                  key: mysql-database
          # 컨테이너 내에서 어떤 경로를 볼륨으로 사용할 지 지정
          volumeMounts:
            - name: mysql-persistent-storage # 밑에서 설정할 volumes.name과 값이 같아야 함
              mountPath: /var/lib/mysql # mysql 컨테이너 내부에 있는 경로
      # 파드가 사용할 볼륨을 지정
      volumes:
        - name: mysql-persistent-storage # 위에서 설정할 volumeMounts.name과 일치해야 함
          persistentVolumeClaim:
            claimName: mysql-pvc # 연결시킬 PVC의 name과 동일해야 함
